SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `heizung` DEFAULT CHARACTER SET utf8 ;
USE `heizung` ;

-- -----------------------------------------------------
-- Table `heizung`.`wp_data`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `heizung`.`wp_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `FailureTempFlow` FLOAT NOT NULL ,
  `WarningsDiv` INT(11) NOT NULL ,
  `PoolTempNominal` FLOAT NOT NULL ,
  `SolarTempNominalMin` FLOAT NOT NULL ,
  `ReturnTempNominal` FLOAT NOT NULL ,
  `AuxiliaryHeatMode` TINYINT(4) NOT NULL ,
  `HeatCharacteristicLimit` FLOAT NOT NULL ,
  `OHDomesticWaterCompressor` FLOAT NOT NULL ,
  `HeatOff` TINYINT(1) NOT NULL ,
  `PSourcePump` FLOAT NOT NULL ,
  `Hysteresis` FLOAT NOT NULL ,
  `Pincode` INT(11) NOT NULL ,
  `OHCooling` FLOAT NOT NULL ,
  `CondensationTemp` FLOAT NOT NULL ,
  `ModemType` TINYINT(4) NOT NULL ,
  `OHCompressor2` FLOAT NOT NULL ,
  `PoolMaxRunTime` TINYINT(4) NOT NULL ,
  `RoomTempFactor` TINYINT(4) NOT NULL ,
  `SourcePumpPreRunPeriod` TINYINT(4) NOT NULL ,
  `OHPoolCompressor` FLOAT NOT NULL ,
  `ScreedTempNominal` FLOAT NOT NULL ,
  `HeatingUpScreed` TINYINT(1) NOT NULL ,
  `DomesticWaterTimeOff` TIME NOT NULL ,
  `Failure` INT(11) NOT NULL ,
  `ServicePool` TINYINT(1) NOT NULL ,
  `PoolTimeDelayOnSolar` TINYINT(4) NOT NULL ,
  `LegionellaTimeOn` TIME NOT NULL ,
  `DWNumberOfCompressors` TINYINT(4) NOT NULL ,
  `WarningsOthers` INT(11) NOT NULL ,
  `Pelectric` FLOAT NOT NULL ,
  `AuxilaryModeHeating` TINYINT(4) NOT NULL ,
  `CondensationPress` FLOAT NOT NULL ,
  `FailureTempPool` FLOAT NOT NULL ,
  `OperatingHoursValue` FLOAT NOT NULL ,
  `EvaporationPress` FLOAT NOT NULL ,
  `PoolOff` TINYINT(1) NOT NULL ,
  `HeatSourceOut` FLOAT NOT NULL ,
  `HeatTempHyst` FLOAT NOT NULL ,
  `DOManualOperatingModeOn` VARCHAR(16) NOT NULL ,
  `SolarTempActual` FLOAT NOT NULL ,
  `LCD_Display_Line_1` VARCHAR(16) NOT NULL ,
  `WarningInMask` VARCHAR(16) NOT NULL ,
  `OHDomesticWaterAuxilary` FLOAT NOT NULL ,
  `DomesticWaterTemp` FLOAT NOT NULL ,
  `SelectedValue` INT(11) NOT NULL ,
  `OHHeatingCompressor` FLOAT NOT NULL ,
  `SolarTempHyst` FLOAT NOT NULL ,
  `SolarTimeOn` TIME NOT NULL ,
  `SolarOff` TINYINT(1) NOT NULL ,
  `ServiceAuxiliaryHeating` TINYINT(1) NOT NULL ,
  `HeatingCircuitTemp` FLOAT NOT NULL ,
  `OffsetPn` FLOAT NOT NULL ,
  `HeatCharacteristicGradient` FLOAT NOT NULL ,
  `LCD_Display_Line_2` VARCHAR(16) NOT NULL ,
  `SoftwareReset` TINYINT(1) NOT NULL ,
  `HeatingPumpPreRunPeriod` TINYINT(4) NOT NULL ,
  `ManufSerialNum` VARCHAR(16) NOT NULL ,
  `NDStatus` TINYINT(4) NOT NULL ,
  `HeatSourceIn` FLOAT NOT NULL ,
  `SolarTimeOff` TIME NOT NULL ,
  `CharacteristicGradient` FLOAT NOT NULL ,
  `HeatReturnTemp` FLOAT NOT NULL ,
  `Ta` TINYINT(4) NOT NULL ,
  `DomesticWaterTimeDelayOnSolar` TINYINT(4) NOT NULL ,
  `OperatingStartTime` TIME NOT NULL ,
  `CoolTimeOn` TIME NOT NULL ,
  `CommMode` TINYINT(4) NOT NULL ,
  `OHHeatingAuxilary` FLOAT NOT NULL ,
  `SetManufSerialNum` VARCHAR(16) NOT NULL ,
  `SetManufType` VARCHAR(16) NOT NULL ,
  `OHSolar` FLOAT NOT NULL ,
  `DomesticWaterTimeOn` TIME NOT NULL ,
  `Kp` FLOAT NOT NULL ,
  `AutomaticOffDownUpSwitch` TINYINT(4) NOT NULL ,
  `WarningsInput` INT(11) NOT NULL ,
  `SolarSensor` TINYINT(4) NOT NULL ,
  `RoomTempNominal` FLOAT NOT NULL ,
  `HeatIncreaseTimeOn` TIME NOT NULL ,
  `FailureTimeStampDATE` DATETIME NOT NULL ,
  `OutdoorTemp24h` FLOAT NOT NULL ,
  `WarningsOutput` INT(11) NOT NULL ,
  `PoolTimeOff` TIME NOT NULL ,
  `ServiceDomesticWater` TINYINT(1) NOT NULL ,
  `HeatCharacteristicSetPointBaseTemp` FLOAT NOT NULL ,
  `CoolOff` TINYINT(1) NOT NULL ,
  `LngSelect` INT(11) NOT NULL ,
  `NumberOfCompressors` TINYINT(4) NOT NULL ,
  `View` TINYINT(4) NOT NULL ,
  `FailureTempOutdoor` FLOAT NOT NULL ,
  `ExtControlCode` INT(11) NOT NULL ,
  `OperatingHoursSelector` TINYINT(4) NOT NULL ,
  `PoolNumberOfCompressors` TINYINT(4) NOT NULL ,
  `FirmwareDate` VARCHAR(16) NOT NULL ,
  `HeatingPumpAfterRunPeriod` TINYINT(4) NOT NULL ,
  `SelectedYear` INT(11) NOT NULL ,
  `FailureTempDomesticWater` FLOAT NOT NULL ,
  `SetDefaultSettings` TINYINT(4) NOT NULL ,
  `CyclicMeasurementPeriod` TINYINT(4) NOT NULL ,
  `CoolReturnTempHyst` FLOAT NOT NULL ,
  `CharacteristicLimit` FLOAT NOT NULL ,
  `PoolTempHyst` FLOAT NOT NULL ,
  `SunctionGasTemp` FLOAT NOT NULL ,
  `RoomTemp1h` FLOAT NOT NULL ,
  `ServiceCooling` TINYINT(1) NOT NULL ,
  `ManufType` VARCHAR(16) NOT NULL ,
  `CoolTimeOff` TIME NOT NULL ,
  `CoolCharacteristicSetPoint` FLOAT NOT NULL ,
  `OHCompressor1` FLOAT NOT NULL ,
  `FailureTempSuctionGas` FLOAT NOT NULL ,
  `DomesticWaterTempNominal` FLOAT NOT NULL ,
  `Ringtones` TINYINT(4) NOT NULL ,
  `HeatIncreaseTimeOff` TIME NOT NULL ,
  `AuxilaryMaxDifference` FLOAT NOT NULL ,
  `FlowTemp` FLOAT NOT NULL ,
  `OperatingStopTime` TIME NOT NULL ,
  `Tn` TINYINT(4) NOT NULL ,
  `AuxiliaryHeatTempLimitSourceIn` FLOAT NOT NULL ,
  `WarningOutMask` INT(11) NOT NULL ,
  `OutdoorTemp` FLOAT NOT NULL ,
  `Interruption` INT(11) NOT NULL ,
  `DomesticWaterTempActual` FLOAT NOT NULL ,
  `HeatReturnTempNominal` FLOAT NOT NULL ,
  `DomesticWaterOff` TINYINT(1) NOT NULL ,
  `FailureEvaporationTemp` FLOAT NOT NULL ,
  `CoolReturnTempNominal` FLOAT NOT NULL ,
  `ServiceSolar` TINYINT(1) NOT NULL ,
  `FailureTempHeatSourceOut` FLOAT NOT NULL ,
  `SolarTemp` FLOAT NOT NULL ,
  `FailureTempSolar` FLOAT NOT NULL ,
  `HeatCharacteristicSetPoint` FLOAT NOT NULL ,
  `Refrigerant` TINYINT(4) NOT NULL ,
  `OffsetPh` FLOAT NOT NULL ,
  `HeatIncreaseSetPtOffset` FLOAT NOT NULL ,
  `ReturnTemp` FLOAT NOT NULL ,
  `TimeScaler` FLOAT NOT NULL ,
  `SolarTempReturn` FLOAT NOT NULL ,
  `HeatTimeOn` TIME NOT NULL ,
  `OutdoorTemp1h` FLOAT NOT NULL ,
  `FailureTempReturn` FLOAT NOT NULL ,
  `EvaporationTemp` FLOAT NOT NULL ,
  `ServiceMixer` TINYINT(1) NOT NULL ,
  `PowerValue` FLOAT NOT NULL ,
  `WarningOthersMask` INT(11) NOT NULL ,
  `PoolTimeOn` TIME NOT NULL ,
  `ADC_Error` INT(11) NOT NULL ,
  `FailureOperatingMode` VARCHAR(16) NOT NULL ,
  `CoolReturnTemp` FLOAT NOT NULL ,
  `LegionellaTimeOff` TIME NOT NULL ,
  `RTCTime` DATETIME NOT NULL ,
  `RTCDate` DATETIME NOT NULL ,
  `FirmwareVersion` VARCHAR(16) NOT NULL ,
  `Pthermal` FLOAT NOT NULL ,
  `RoomTemp` FLOAT NOT NULL ,
  `HeatingCircuitNominal` FLOAT NOT NULL ,
  `FailureDIBuffer` INT(11) NOT NULL ,
  `COP` FLOAT NOT NULL ,
  `LegionellaSchedule` TINYINT(4) NOT NULL ,
  `PoolTemp` FLOAT NOT NULL ,
  `CharacteristicSetPointBaseTemp` FLOAT NOT NULL ,
  `DOExtStatus` TINYINT(4) NOT NULL ,
  `HeatTimeOff` TIME NOT NULL ,
  `FailureCondensationTemp` FLOAT NOT NULL ,
  `WarningDivMask` INT(11) NOT NULL ,
  `FailureDOBuffer` INT(11) NOT NULL ,
  `FailureAIError` INT(11) NOT NULL ,
  `HeatIncreaseOff` TINYINT(1) NOT NULL ,
  `FailureTimeStampTIME` DATETIME NOT NULL ,
  `FailureTempHeatSourceIn` FLOAT NOT NULL ,
  `LegionellaTempNominal` FLOAT NOT NULL ,
  `DomesticWaterTempHyst` FLOAT NOT NULL ,
  `DOBuffer` INT(11) NOT NULL ,
  `OperatingState` INT(11) NOT NULL ,
  `PoolTempActual` FLOAT NOT NULL ,
  `ServiceHeating` TINYINT(1) NOT NULL ,
  `DIBuffer` INT(11) NOT NULL ,
  `HeatSourceMinT` TINYINT(4) NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `wpdata_timestamp` (`timestamp` ASC) )
ENGINE = MyISAM
AUTO_INCREMENT = 272914
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heizung`.`wp_write_data`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `heizung`.`wp_write_data` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  `user` VARCHAR(16) NULL ,
  `key` VARCHAR(255) NOT NULL ,
  `old_value` VARCHAR(45) NULL ,
  `new_value` VARCHAR(45) NOT NULL ,
  `status` ENUM('pending','success','fail','outdated') NOT NULL DEFAULT 'pending' ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

USE `heizung` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
