-- -----------------------------------------------------
-- Table `heizung`.`wp_data`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS wp_data (
id INT NOT NULL auto_increment,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FailureTempFlow FLOAT NOT NULL,
WarningsDiv INT NOT NULL,
PoolTempNominal FLOAT NOT NULL,
SolarTempNominalMin FLOAT NOT NULL,
ReturnTempNominal FLOAT NOT NULL,
AuxiliaryHeatMode TINYINT NOT NULL,
HeatCharacteristicLimit FLOAT NOT NULL,
OHDomesticWaterCompressor FLOAT NOT NULL,
HeatOff BOOLEAN NOT NULL,
PSourcePump FLOAT NOT NULL,
Hysteresis FLOAT NOT NULL,
Pincode INT NOT NULL,
OHCooling FLOAT NOT NULL,
CondensationTemp FLOAT NOT NULL,
ModemType TINYINT NOT NULL,
OHCompressor2 FLOAT NOT NULL,
PoolMaxRunTime TINYINT NOT NULL,
RoomTempFactor TINYINT NOT NULL,
SourcePumpPreRunPeriod TINYINT NOT NULL,
OHPoolCompressor FLOAT NOT NULL,
ScreedTempNominal FLOAT NOT NULL,
HeatingUpScreed BOOLEAN NOT NULL,
DomesticWaterTimeOff TIME NOT NULL,
Failure INT NOT NULL,
ServicePool BOOLEAN NOT NULL,
PoolTimeDelayOnSolar TINYINT NOT NULL,
LegionellaTimeOn TIME NOT NULL,
DWNumberOfCompressors TINYINT NOT NULL,
WarningsOthers INT NOT NULL,
Pelectric FLOAT NOT NULL,
AuxilaryModeHeating TINYINT NOT NULL,
CondensationPress FLOAT NOT NULL,
FailureTempPool FLOAT NOT NULL,
OperatingHoursValue FLOAT NOT NULL,
EvaporationPress FLOAT NOT NULL,
PoolOff BOOLEAN NOT NULL,
HeatSourceOut FLOAT NOT NULL,
HeatTempHyst FLOAT NOT NULL,
DOManualOperatingModeOn INT NOT NULL,
SolarTempActual FLOAT NOT NULL,
LCD_Display_Line_1 VARCHAR(16) NOT NULL,
WarningInMask INT NOT NULL,
OHDomesticWaterAuxilary FLOAT NOT NULL,
DomesticWaterTemp FLOAT NOT NULL,
SelectedValue INT NOT NULL,
OHHeatingCompressor FLOAT NOT NULL,
SolarTempHyst FLOAT NOT NULL,
SolarTimeOn TIME NOT NULL,
SolarOff BOOLEAN NOT NULL,
ServiceAuxiliaryHeating BOOLEAN NOT NULL,
HeatingCircuitTemp FLOAT NOT NULL,
OffsetPn FLOAT NOT NULL,
HeatCharacteristicGradient FLOAT NOT NULL,
LCD_Display_Line_2 VARCHAR(16) NOT NULL,
SoftwareReset BOOLEAN NOT NULL,
HeatingPumpPreRunPeriod TINYINT NOT NULL,
ManufSerialNum VARCHAR(16) NOT NULL,
NDStatus TINYINT NOT NULL,
HeatSourceIn FLOAT NOT NULL,
SolarTimeOff TIME NOT NULL,
CharacteristicGradient FLOAT NOT NULL,
HeatReturnTemp FLOAT NOT NULL,
Ta TINYINT NOT NULL,
DomesticWaterTimeDelayOnSolar TINYINT NOT NULL,
OperatingStartTime TIME NOT NULL,
CoolTimeOn TIME NOT NULL,
CommMode TINYINT NOT NULL,
OHHeatingAuxilary FLOAT NOT NULL,
SetManufSerialNum VARCHAR(16) NOT NULL,
SetManufType VARCHAR(16) NOT NULL,
OHSolar FLOAT NOT NULL,
DomesticWaterTimeOn TIME NOT NULL,
Kp FLOAT NOT NULL,
AutomaticOffDownUpSwitch TINYINT NOT NULL,
WarningsInput INT NOT NULL,
SolarSensor TINYINT NOT NULL,
RoomTempNominal FLOAT NOT NULL,
HeatIncreaseTimeOn TIME NOT NULL,
FailureTimeStampDATE DATETIME NOT NULL,
OutdoorTemp24h FLOAT NOT NULL,
WarningsOutput INT NOT NULL,
PoolTimeOff TIME NOT NULL,
ServiceDomesticWater BOOLEAN NOT NULL,
HeatCharacteristicSetPointBaseTemp FLOAT NOT NULL,
CoolOff BOOLEAN NOT NULL,
LngSelect INT NOT NULL,
NumberOfCompressors TINYINT NOT NULL,
View TINYINT NOT NULL,
FailureTempOutdoor FLOAT NOT NULL,
ExtControlCode INT NOT NULL,
OperatingHoursSelector TINYINT NOT NULL,
PoolNumberOfCompressors TINYINT NOT NULL,
FirmwareDate VARCHAR(16) NOT NULL,
HeatingPumpAfterRunPeriod TINYINT NOT NULL,
SelectedYear INT NOT NULL,
FailureTempDomesticWater FLOAT NOT NULL,
SetDefaultSettings TINYINT NOT NULL,
CyclicMeasurementPeriod TINYINT NOT NULL,
CoolReturnTempHyst FLOAT NOT NULL,
CharacteristicLimit FLOAT NOT NULL,
PoolTempHyst FLOAT NOT NULL,
SunctionGasTemp FLOAT NOT NULL,
RoomTemp1h FLOAT NOT NULL,
ServiceCooling BOOLEAN NOT NULL,
ManufType VARCHAR(16) NOT NULL,
CoolTimeOff TIME NOT NULL,
CoolCharacteristicSetPoint FLOAT NOT NULL,
OHCompressor1 FLOAT NOT NULL,
FailureTempSuctionGas FLOAT NOT NULL,
DomesticWaterTempNominal FLOAT NOT NULL,
Ringtones TINYINT NOT NULL,
HeatIncreaseTimeOff TIME NOT NULL,
AuxilaryMaxDifference FLOAT NOT NULL,
FlowTemp FLOAT NOT NULL,
OperatingStopTime TIME NOT NULL,
Tn TINYINT NOT NULL,
AuxiliaryHeatTempLimitSourceIn FLOAT NOT NULL,
WarningOutMask INT NOT NULL,
OutdoorTemp FLOAT NOT NULL,
Interruption INT NOT NULL,
DomesticWaterTempActual FLOAT NOT NULL,
HeatReturnTempNominal FLOAT NOT NULL,
DomesticWaterOff BOOLEAN NOT NULL,
FailureEvaporationTemp FLOAT NOT NULL,
CoolReturnTempNominal FLOAT NOT NULL,
ServiceSolar BOOLEAN NOT NULL,
FailureTempHeatSourceOut FLOAT NOT NULL,
SolarTemp FLOAT NOT NULL,
FailureTempSolar FLOAT NOT NULL,
HeatCharacteristicSetPoint FLOAT NOT NULL,
Refrigerant TINYINT NOT NULL,
OffsetPh FLOAT NOT NULL,
HeatIncreaseSetPtOffset FLOAT NOT NULL,
ReturnTemp FLOAT NOT NULL,
TimeScaler FLOAT NOT NULL,
SolarTempReturn FLOAT NOT NULL,
HeatTimeOn TIME NOT NULL,
OutdoorTemp1h FLOAT NOT NULL,
FailureTempReturn FLOAT NOT NULL,
EvaporationTemp FLOAT NOT NULL,
ServiceMixer BOOLEAN NOT NULL,
PowerValue FLOAT NOT NULL,
WarningOthersMask INT NOT NULL,
PoolTimeOn TIME NOT NULL,
ADC_Error INT NOT NULL,
FailureOperatingMode INT NOT NULL,
CoolReturnTemp FLOAT NOT NULL,
LegionellaTimeOff TIME NOT NULL,
RTCTime DATETIME NOT NULL,
RTCDate DATETIME NOT NULL,
FirmwareVersion VARCHAR(16) NOT NULL,
Pthermal FLOAT NOT NULL,
RoomTemp FLOAT NOT NULL,
HeatingCircuitNominal FLOAT NOT NULL,
FailureDIBuffer INT NOT NULL,
COP FLOAT NOT NULL,
LegionellaSchedule TINYINT NOT NULL,
PoolTemp FLOAT NOT NULL,
CharacteristicSetPointBaseTemp FLOAT NOT NULL,
DOExtStatus TINYINT NOT NULL,
HeatTimeOff TIME NOT NULL,
FailureCondensationTemp FLOAT NOT NULL,
WarningDivMask INT NOT NULL,
FailureDOBuffer INT NOT NULL,
FailureAIError INT NOT NULL,
HeatIncreaseOff BOOLEAN NOT NULL,
FailureTimeStampTIME DATETIME NOT NULL,
FailureTempHeatSourceIn FLOAT NOT NULL,
LegionellaTempNominal FLOAT NOT NULL,
DomesticWaterTempHyst FLOAT NOT NULL,
DOBuffer INT NOT NULL,
OperatingState INT NOT NULL,
PoolTempActual FLOAT NOT NULL,
ServiceHeating BOOLEAN NOT NULL,
DIBuffer INT NOT NULL,
HeatSourceMinT TINYINT NOT NULL,
 PRIMARY KEY (id),
 INDEX wpdata_timestamp (timestamp)
 )
ENGINE = InnoDB
AUTO_INCREMENT = 272914
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wp_write_data`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `wp_write_data` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  `user` VARCHAR(16) NULL ,
  `key` VARCHAR(255) NOT NULL ,
  `old_value` VARCHAR(45) NULL ,
  `new_value` VARCHAR(45) NOT NULL ,
  `status` ENUM('pending','success','fail','outdated') NOT NULL DEFAULT 'pending' ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

