<?php
$title = 'Heating';
$this->headTitle($title);

// load style sheet
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.css'));
$this->headLink()->appendStylesheet($this->basePath('css/styles.css'));

// load javascript
$this->inlineScript()->appendFile($this->basePath('js/sprintf.js'));
$this->inlineScript()->appendFile($this->basePath('js/jquery-ui.min.js'));
$this->inlineScript()->appendFile($this->basePath('js/jquery.jeditable.mini.js'));
$this->inlineScript()->appendFile($this->basePath('js/jquery-ui-timepicker-addon.js'));
$this->inlineScript()->appendFile($this->basePath('js/general.js'));

?>
    <!-- Date and Time Selector -->
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Overview</a></li>
            <li><a href="#tabs-2">Heating</a></li>
            <li><a href="#tabs-3">Cooling</a></li>
            <li><a href="#tabs-4">Hot Water</a></li>
        </ul>
        <div id="tabs-1">
            <div id="diagram">
            <img src="/img/thome.gif" class="picture" id="home"><br>
            
            <!-- Temperatures -->
            <div id="outdoortemp"><span id="description_short"></span><span class="value blackText" id="outdoortemp"></span></div><br>
            <div id="outdoortemp1h"><span id="description_short"></span><span class="value blackText" id="outdoortemp1h"></span></div><br>
            <div id="outdoortemp24h"><span id="description_short"></span><span class="value blacktext" id="outdoortemp24h"></span></div><br>
            
            <div id="roomtempnominal"><span id="description_short"></span><span class="value redtext edit" id="roomtempnominal"></span></div><br>
            <div id="roomtemp"><span id="description_short"></span><span class="value blacktext" id="roomtemp"></span></div><br>
            <div id="roomtemp1h"><span id="description_short"></span><span class="value blacktext" id="roomtemp1h"></span></div><br>
            
            <!-- general -->
            <div id="rtcdate"><span id="description"></span><span class="value blacktext date" id="rtcdate"></span></div><br>
            <div id="rtctime"><span id="description"></span><span class="value blacktext time" id="rtctime"></span></div><br>
            <div id="firmwareversion"><span id="description_short"></span><span class="value blacktext" id="firmwareversion"></div><br>
            <div id="firmwaredate"><span id="description_short"></span><span class="value blacktext" id="firmwaredate"></div><br>

            <!--  consumption -->
            <div class="blacktext" id="pelectric"><span id="description"></span><span id="pelectric"></div><br>
            <div class="blacktext" id="pthermal"><span id="description"></span><span id="pthermal"></div><br>
            <div class="blacktext" id="cop"><span id="description"></span><span id="cop"></div><br>

            <img src="img/ds_std.gif" class="picture" id="background"><br>
            <!-- heatsource -->
            <div id="heatsourcein"><span class="value redtext" id="heatsourcein"></span></div><br>
            <div id="heatsourceout"><span class="value bluetext" id="heatsourceout"></span></div><br>
            <div id="iconpumpheatsource"><img alt="" src="/img/pump_90rgb.ico"></div><br>
            <!-- condensator -->
            <div id="condensationtemp"><span class="value redtext" id="condensationtemp"></span></div><br>
            <div id="condensationpress"><span class="value redtext" id="condensationpress"></span></div><br>
            <!-- middle -->
            <div id="sunctiongastemp"><span class="value blacktext" id="sunctiongastemp"></span></div><br>
            <div id="ohcompressor1"><span class="value blacktext" id="ohcompressor1"></span></div><br>
            <div id="iconcompressor1"><img alt="" src="/img/refrig_0rgb.ico"></div><br>
            <div id="iconmagnetvalve"><img alt="" src="/img/valve_magn_0rgb.ico"></div><br>
            <!-- evaporator -->
            <div id="evaporationtemp"><span class="value bluetext" id="evaporationtemp"></span></div><br>
            <div id="evaporationpress"><span class="value bluetext" id="evaporationpress"></span></div><br>
            <!-- heattarget -->
            <div id="flowtemp"><span class="value redtext" id="flowtemp"></span></div><br>
            <div id="heatreturntemp2"><span class="value bluetext" id="heatreturntemp2"></span></div><br>
            <div id="iconpumpheating"><img alt="" src="/img/pump_180rgb.ico"></div><br>
        </div>
        </div>
        <div id="tabs-2">
            <div id="heating">
                <!-- heating -->
                <div id="heatoff"><span id="description"></span><span class="blacktext value edit" id="heatoff"></span></div><br>
                <div id="heattimeon"><span id="description"></span><input class="timepicker" id="heattimeon"></div>
                <div id="heattimeoff"><span id="description"></span><input class="blacktext timepicker" id="heattimeoff"></div>
                <div id="heatcharacteristicsetpoint"><span id="description"></span><span class="blacktext value edit" id="heatcharacteristicsetpoint"></span></div><br>
                <div id="heatcharacteristicsetpointbasetemp"><span id="description"></span><span class="blacktext value edit" id="heatcharacteristicsetpointbasetemp"></span></div><br>
                <div id="heatcharacteristicgradient"><span id="description"></span><span class="blacktext value edit" id="heatcharacteristicgradient"></span></div><br>
                <div id="heatcharacteristiclimit"><span id="description"></span><span class="blacktext value edit" id="heatcharacteristiclimit"></div><br>
                <div id="heatreturntemp"><span id="description"></span><span class="blacktext value" id="heatreturntemp"></div><br>
                <div id="heatreturntempnominal"><span id="description"></span><span class="blacktext value" id="heatreturntempnominal"></div><br>
                <div id="heattemphyst"><span id="description"></span><span class="blacktext value edit" id="heattemphyst"></div><br>
                <div id="roomtempnominal"><span id="description"></span><span class="blacktext value edit" id="roomtempnominal"></span></div><br>
                <div id="roomtempfactor"><span id="description"></span><span class="blacktext value edit" id="roomtempfactor"></span></div><br>
                <div id="heatincreaseoff"><span id="description"></span><span class="blacktext value edit" id="heatincreaseoff"></span></div><br>
                <div id="heatincreasetimeon"><span id="description"></span><input class="blacktext timepicker" id="heatincreasetimeon"></div>
                <div id="heatincreasetimeoff"><span id="description"></span><input class="blacktext timepicker" id="heatincreasetimeoff"></div>
                <div id="heatincreasesetptoffset"><span id="description"></span><span class="blacktext value edit" id="heatincreasesetptoffset"></span></div><br>
                <div id="auxilarymodeheating"><span id="description"></span><span class="blacktext value" id="auxilarymodeheating"></span></div><br>
                <div id="auxilarymaxdifference"><span id="description"></span><span class="blacktext value" id="auxilarymaxdifference"></span></div><br>
            </div>
        </div>
        <div id="tabs-3">
            <div id="cooling">
                <!-- cooling -->
                <div id="cooloff"><span id="description"></span><span class="blacktext value edit" id="cooloff"></span></div><br>
                <div id="cooltimeon"><span id="description"></span><input class="blacktext timepicker" id="cooltimeon"></div>
                <div id="cooltimeoff"><span id="description"></span><input class="blacktext timepicker" id="cooltimeoff"></span></div>
                <div id="coolcharacteristicsetpoint"><span id="description"></span><span class="blacktext value edit" id="coolcharacteristicsetpoint"></span></div><br>
                <div id="coolreturntemp"><span id="description"></span><span class="blacktext value" id="coolreturntemp"></span></div><br>
                <div id="coolreturntempnominal"><span id="description"></span><span class="blacktext value edit" id="coolreturntempnominal"></span></div><br>
                <div id="coolreturntemphyst"><span id="description"></span><span class="blacktext value edit" id="coolreturntemphyst"></div><br>
            </div>
        </div>
        <div id="tabs-4">
            <div id="hotwater">
                <!-- hot water -->
                <div id="domesticwateroff"><span id="description"></span><span class="blacktext value edit" id="domesticwateroff"></span></div><br>
                <div id="domesticwatertimeon"><span id="description"></span><input class="blacktext timepicker" id="domesticwatertimeon"></div>
                <div id="domesticwatertimeoff"><span id="description"></span><input class="blacktext timepicker" id="domesticwatertimeoff"></div>
                <div id="domesticwatertempactual"><span id="description"></span><span class="blacktext value" id="domesticwatertempactual"></span></div><br>
                <div id="domesticwatertempnominal"><span id="description"></span><span class="blacktext value edit" id="domesticwatertempnominal"></span></div><br>
                <div id="domesticwatertemphyst"><span id="description"></span><span class="blacktext value edit" id="domesticwatertemphyst"></span></div><br>
                <div id="legionellaschedule"><span id="description"></span><span class="blacktext value edit" id="legionellaschedule"></div><br>
                <div id="legionellatimeon"><span id="description"></span><input class="blacktext timepicker" id="legionellatimeon"></div>
                <div id="legionellatimeoff"><span id="description"></span><input class="blacktext timepicker" id="legionellatimeoff"></div>
                <div id="legionellatempnominal"><span id="description"></span><span class="blacktext value edit" id="legionellatempnominal"></div><br>
                <div id="dwnumberofcompressors"><span id="description"></span><span class="blacktext value" id="dwnumberofcompressors"></div><br>
                <div id="domesticwatertimedelayonsolar"><span id="description"></span><span class="blacktext value" id="domesticwatertimedelayonsolar"></div><br>
            </div>
        </div>
    </div>
    <div id="overview">
        <div id="datetimefield"><span id="description"></span><span><input class="test" placeholder="Select a date to filter" type="text" id="datetimepicker"></span></div><br>
        <br>
        <!-- status and values -->
        <div id="iconcooling"><img alt="" src="/img/cool_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="coolreturntempnominal"><span class="edit" id="coolreturntempnominal"></span></div><br>
        <div class="value blacktext" id="coolreturntemp"><span id="coolreturntemp"></span></div><br>

        <div id="iconheating"><img alt="" src="/img/heat_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="heatreturntempnominal"><span class="" id="heatreturntempnominal"></span></div><br>
        <div class="value blacktext" id="heatreturntemp"><span id="heatreturntemp"></span></div><br>

        <div id="icondomesticwater"><img alt="" src="/img/hw_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="domesticwatertempnominal"><span class="edit" id="domesticwatertempnominal"></span></div><br>
        <div class="value blacktext" id="domesticwatertempactual"><span id="domesticwatertempactual"></span></div><br>

        <div id="iconpool"><img alt="" src="/img/pool_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="pooltempnominal"><span class="edit" id="pooltempnominal"></span></div><br>
        <div class="value blacktext" id="pooltempactual"><span id="pooltempactual"></span></div><br>

        <div id="iconsolar"><img alt="" src="/img/solar_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="solartempnominalmin"><span class="edit" id="solartempnominalmin"></span></div><br>
        <div class="value blacktext" id="solartempactual"><span id="solartempactual"></span></div><br>

        <div id="icon3way"><img alt="" src="/img/3way_32x32_inactive.ico"></div><br>
        <div class="value targettext" id="heatingcircuitnominal"><span class="edit" id="heatingcircuitnominal"></span></div><br>
         <div class="value blacktext" id="heatingcircuittemp"><span id="heatingcircuittemp"></span></div><br>
    </div>
